/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ASM;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.runtime.JSType;

/**
 *
 * @author hoang
 */
public class QLDiemSinhVien extends javax.swing.JFrame {

    /**
     * Creates new form QLDiemSinhVien
     */
    Connection cn;
    ArrayList<DiemSinhvien> list = new ArrayList<>();
   // ArrayList<DiemSinhvien> listtop3 = new ArrayList<>();
    DefaultTableModel model;
    int index = 0;

    public QLDiemSinhVien() {
        initComponents();
        setTitle("Quản lý điểm Sinh viên");
        setLocationRelativeTo(null);
        setResizable(false);
        model = (DefaultTableModel) tblkq.getModel();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cn = SQL.DAO("ASMjava3");
        if (cn != null) {
            LoadDataToList();
            top3();
            displayList(0);
        } else {
            JOptionPane.showMessageDialog(this, "kết nối thất bại");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        btntimkiem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblhoten = new javax.swing.JLabel();
        txtmasv = new javax.swing.JTextField();
        txttienganh = new javax.swing.JTextField();
        txttinhoc = new javax.swing.JTextField();
        txtgdtc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lbltb = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnnew = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkq = new javax.swing.JTable();
        btndau = new javax.swing.JButton();
        btnlen = new javax.swing.JButton();
        btnxuong = new javax.swing.JButton();
        btncuoi = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblso = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Quản Lý Điểm Sinh Viên");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Mã SV:");

        btntimkiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btntimkiem.setForeground(new java.awt.Color(0, 51, 204));
        btntimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search.png"))); // NOI18N
        btntimkiem.setText("Search");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txttimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btntimkiem)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Họ tên SV:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Mã SV:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Tiếng anh:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tin học:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Giáo dục TC:");

        lblhoten.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblhoten.setForeground(new java.awt.Color(0, 102, 204));

        txttienganh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttienganhMouseClicked(evt);
            }
        });

        txtgdtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgdtcActionPerformed(evt);
            }
        });
        txtgdtc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtgdtcKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Điểm TB:");

        lbltb.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbltb.setForeground(new java.awt.Color(0, 0, 255));
        lbltb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtgdtc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(txttinhoc, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txttienganh, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtmasv, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lblhoten, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(lblhoten, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txttienganh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txttinhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtgdtc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addContainerGap())
        );

        jPanel3.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        btnnew.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnnew.setForeground(new java.awt.Color(0, 51, 255));
        btnnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        btnnew.setText("New");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });
        jPanel3.add(btnnew);

        btnsave.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnsave.setForeground(new java.awt.Color(0, 51, 255));
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save.png"))); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnsave);

        btndelete.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btndelete.setForeground(new java.awt.Color(0, 51, 255));
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btndelete);

        btnupdate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(0, 51, 255));
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit.png"))); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnupdate);

        tblkq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ tên", "Tiếng anh", "Tin học", "GDTC", "Điểm TB"
            }
        ));
        tblkq.setGridColor(new java.awt.Color(204, 204, 204));
        tblkq.setRowHeight(40);
        tblkq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkqMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblkq);

        btndau.setIcon(new javax.swing.ImageIcon("D:\\JAVA3\\src\\Images\\Len (2).png")); // NOI18N
        btndau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndauActionPerformed(evt);
            }
        });

        btnlen.setIcon(new javax.swing.ImageIcon("D:\\JAVA3\\src\\Images\\len1.png")); // NOI18N
        btnlen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlenActionPerformed(evt);
            }
        });

        btnxuong.setIcon(new javax.swing.ImageIcon("D:\\JAVA3\\src\\Images\\Xuong1.png")); // NOI18N
        btnxuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuongActionPerformed(evt);
            }
        });

        btncuoi.setIcon(new javax.swing.ImageIcon("D:\\JAVA3\\src\\Images\\Xuong (2).png")); // NOI18N
        btncuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuoiActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("3 Sinh viên có điểm cao nhất");

        lblso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblso.setForeground(new java.awt.Color(255, 0, 0));
        lblso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btndau, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnlen, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnxuong, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btncuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnxuong, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncuoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnlen, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btndau, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblso, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void LoadDataToList() {
        try {
            list.clear();
            String sql = "Select * from STUDENTS left join GARADE on STUDENTS.masv=GARADE.masv";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                list.add(new DiemSinhvien(rs.getString(1), rs.getString(2), rs.getFloat(10), rs.getFloat(11), rs.getFloat(12)));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void top3() {
        try {
            model.setRowCount(0);
            //listtop3.clear();
            String sql = "select top 3 *, (tinhoc+tienganh+gdtc)/3 as tb from STUDENTS left join GARADE on STUDENTS.masv=GARADE.masv "
                    + "order by tb desc";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                //listtop3.add(new DiemSinhvien(rs.getString(1), rs.getString(2), rs.getFloat(10), rs.getFloat(11), rs.getFloat(12)));
                String tb = String.format("%.1f", (rs.getFloat(10) + rs.getFloat(11) + rs.getFloat(12)) / 3);
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getFloat(10), rs.getFloat(11), rs.getFloat(12), tb});
            }
            //filltable();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

//    void filltable() {
//        model.setRowCount(0);
//        listtop3.forEach((x) -> model.addRow(new Object[]{x.getMasv(), x.getHoten(), x.getTA(), x.getTH(), x.getGDTC(), x.diemTB()}));
//    }
    private void txtgdtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgdtcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgdtcActionPerformed

    private void btnxuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuongActionPerformed
        index++;
        if (index == list.size()) {
            index = 0;
        }
        displayList(index);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnxuongActionPerformed
    void displayList(int vitri) {
        txtmasv.setEditable(false);
        DiemSinhvien sv = list.get(vitri);
        lblhoten.setText(sv.getHoten());
        txtmasv.setText(sv.getMasv());
        txttienganh.setText(String.valueOf(sv.getTA()));
        txttinhoc.setText(String.valueOf(sv.getTH()));
        txtgdtc.setText(String.valueOf(sv.getGDTC()));
        lbltb.setText(String.valueOf(sv.diemTB()));
        lblso.setText((vitri+1)+" / "+list.size());
    }
    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        try {
            boolean co = false;
            if (txttimkiem.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Chưa nhập mã sv muốn tìm");
                co = true;
                return;
            }
            for (int i = 0; i < list.size(); i++) {
                if (list.get(i).getMasv().equalsIgnoreCase(txttimkiem.getText())) {
                    index = i;
                    displayList(index);
                    co = true;
                    break;
                }
            }
            if (co == false) {
                JOptionPane.showMessageDialog(this, "k có sinh viên");
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btntimkiemActionPerformed
    Boolean check() {

        if (txtmasv.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "mã sv bị trống");
            txtmasv.requestFocus();
            return false;
        }
        if (txttienganh.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "điểm tiếng anh trống");
            txttienganh.requestFocus();
            return false;
        }
        try {
            Float.parseFloat(txttienganh.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "điểm tiếng anh phải là số");
            txttienganh.requestFocus();
            return false;
        }
        if (txttinhoc.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "điểm tin học trống");
            txttinhoc.requestFocus();
            return false;
        }
        try {
            Float.parseFloat(txttinhoc.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "điểm tin học phải là số");
            txttinhoc.requestFocus();
            return false;
        }
        if (txtgdtc.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "điểm GDTC trống");
            txtgdtc.requestFocus();
            return false;
        }
        try {
            Float.parseFloat(txtgdtc.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "điểm GDTC phải là số");
            txtgdtc.requestFocus();
            return false;
        }
        return true;
    }
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        try {
            if (check()) {
                String check = "select masv from GARADE";
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(check);
                while (rs.next()) {
                    if (rs.getString(1).equals(txtmasv.getText())) {
                        JOptionPane.showMessageDialog(this, "mã sv bị trùng");
                        return;
                    }
                }
                String them = "insert into GARADE values (?,?,?,?)";
                PreparedStatement pst = cn.prepareStatement(them);
                pst.setString(1, txtmasv.getText());
                pst.setString(2, txttienganh.getText());
                pst.setString(3, txttinhoc.getText());
                pst.setString(4, txtgdtc.getText());
                int row = pst.executeUpdate();
                if (row > 0) {
                    JOptionPane.showMessageDialog(this, "thêm thành công");
                    LoadDataToList();
                    top3();
                } else {
                    JOptionPane.showMessageDialog(this, "thêm thất bại");
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndauActionPerformed
        displayList(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btndauActionPerformed

    private void btncuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuoiActionPerformed

        displayList(list.size() - 1);// TODO add your handling code here:
    }//GEN-LAST:event_btncuoiActionPerformed

    private void btnlenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlenActionPerformed
        index--;
        if (index == -1) {
            index = list.size() - 1;
        }
        displayList(index);
// TODO add your handling code here:
    }//GEN-LAST:event_btnlenActionPerformed

    private void txttienganhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttienganhMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_txttienganhMouseClicked

    private void txtgdtcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgdtcKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            float tb = (Float.parseFloat(txttienganh.getText()) + Float.parseFloat(txttinhoc.getText()) + Float.parseFloat(txtgdtc.getText())) / 3;
            lbltb.setText(String.format("%.1f", tb));
        }
// TODO add your handling code here:
    }//GEN-LAST:event_txtgdtcKeyPressed
void news(){
    txtgdtc.setText("");
        lblhoten.setText("");
        txtmasv.setText("");
        txttienganh.setText("");
        txttinhoc.setText("");
        txttimkiem.setText("");
        lbltb.setText("");
        txtmasv.setEditable(true);
        top3();
}
    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        news();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnewActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed

        try {
            boolean co = false;
            if (txtmasv.getText().equals("")) {
                String delete = JOptionPane.showInputDialog(this, "Mời nhập mã sv");
                if (delete != null && delete.length() > 0) {
                    for (int i = 0; i < list.size(); i++) {
                        if (list.get(i).getMasv().equalsIgnoreCase(delete)) {
                            int hoi = JOptionPane.showConfirmDialog(this, "có xóa k?", "", JOptionPane.YES_NO_OPTION);
                            if (hoi == JOptionPane.YES_OPTION) {
                                String sql = "delete garade where masv=?";
                                PreparedStatement pst = cn.prepareStatement(sql);
                                pst.setString(1, delete);
                                if (pst.executeUpdate() > 0) {
                                    JOptionPane.showMessageDialog(this, "xóa thành công");
                                    LoadDataToList();
                                    top3();
                                } else {
                                    JOptionPane.showMessageDialog(this, "xóa k thành công");
                                }
                            }
                            co = true;
                        }
                    }
                    if (co == false) {
                        JOptionPane.showMessageDialog(this, "k có sinh viên");
                        return;
                    }
                }
            } else {
                int hoi = JOptionPane.showConfirmDialog(this, "có xóa k?", "", JOptionPane.YES_NO_OPTION);
                if (hoi == JOptionPane.YES_OPTION) {
                    String sql = "delete garade where masv=?";
                    PreparedStatement pst = cn.prepareStatement(sql);
                    pst.setString(1, txtmasv.getText());
                    if (pst.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(this, "xóa thành công");
                        LoadDataToList();
                        top3();
                    } else {
                        JOptionPane.showMessageDialog(this, "xóa k thành công");
                    }
                }
            }
            news();
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed

        try {
            boolean co = false;
            if (txtmasv.getText().equals("")) {
                String update = JOptionPane.showInputDialog(this, "Mời nhập mã sv");
                if (update != null && update.length() > 0) {
                    for (int i = 0; i < list.size(); i++) {
                        if (list.get(i).getMasv().equalsIgnoreCase(update)) {
                            displayList(i);
                            co = true;
                        }
                    }
                    if (co == false) {
                        JOptionPane.showMessageDialog(this, "k có sinh viên");
                        return;
                    }
                }
            } else {
                String sql = "update garade set tienganh=?,tinhoc=?,gdtc=? where masv=?";
                PreparedStatement pst = cn.prepareStatement(sql);
                pst.setFloat(1, Float.parseFloat(txttienganh.getText()));
                pst.setFloat(2, Float.parseFloat(txttinhoc.getText()));
                pst.setFloat(3, Float.parseFloat(txtgdtc.getText()));
                pst.setString(4, txtmasv.getText());
                if (pst.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this, "update thành công");
                    LoadDataToList();
                    top3();
                } else {
                    JOptionPane.showMessageDialog(this, "update  k thành công");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    private void tblkqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkqMouseClicked
        int row=tblkq.getSelectedRow();
        txtmasv.setEditable(false);
        txtmasv.setText((String) tblkq.getValueAt(row, 0));
        lblhoten.setText((String) tblkq.getValueAt(row, 1));
        txttienganh.setText(String.valueOf(tblkq.getValueAt(row, 2)));
        txttinhoc.setText(String.valueOf(tblkq.getValueAt(row, 3)));
        txtgdtc.setText(String.valueOf(tblkq.getValueAt(row, 4)));
        lbltb.setText(String.valueOf(tblkq.getValueAt(row, 5)));
        // TODO add your handling code here:
    }//GEN-LAST:event_tblkqMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDiemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDiemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDiemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDiemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDiemSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncuoi;
    private javax.swing.JButton btndau;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnlen;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnxuong;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblhoten;
    private javax.swing.JLabel lblso;
    private javax.swing.JLabel lbltb;
    private javax.swing.JTable tblkq;
    private javax.swing.JTextField txtgdtc;
    private javax.swing.JTextField txtmasv;
    private javax.swing.JTextField txttienganh;
    private javax.swing.JTextField txttimkiem;
    private javax.swing.JTextField txttinhoc;
    // End of variables declaration//GEN-END:variables
}
